' ===
' Document information helpers
' ===

!$today = %date("yyyy-MM-dd")
!$theme_data ?= {
    "textFont": "Helvetica",
    "codeFont": "Menlo",
    "canvasBackgroundColor": "White",
    "titleFontSize": 16,
    "subtitleFontSize": 14,
    "headerBackgroundColor": "LightSteelBlue",
    "headerFontColor": "Black",
    "headerFontStyle": "Bold",
    "headerFontSize": 13,
    "bodyBackgroundColor": "GhostWhite",
    "bodyFontColor": "DarkSlateGrey",
    "bodyFontSize": 12,
    "labelFontColor": "Black",
    "infoFontSize": 10,
    "containerBackgroundColor": "White",
    "enum_headerBackgroundColor": "IndianRed",
    "enum_bodyBackgroundColor": "LightPink",
    "enum_borderColor": "DarkRed",
    "sequenceDivider_headerBackgroundColor": "Khaki",
    "sequenceDivider_borderColor": "Olive",
    "note_bodyBackgroundColor": "Khaki",
    "note_borderColor": "Olive",
    "note_bodyFontSize": 10,
    "legend_bodyBackgroundColor": "GhostWhite",
    "legend_borderColor": "LightGrey",
    "symbol_borderThickness": 1.5,
    "borderColor": "DarkSlateGrey",
    "arrowColor": "Black",
    "borderThickness": 1.5
}

!procedure $add_header($author="", $revision="", $title="")
    !$header = ""
    !if $author != ""
        !$header = $header + "Author: " + $author + "\n"
    !endif
    !if $revision != "" && $title != ""
        !$header = $header + $title + " Rev. " + $revision_name + "\n"
    !endif

    !if $header != ""
        header $header + "Rendered on " + $today
    !endif
!endprocedure

!procedure $add_footer($company="", $confidential="")
    !$footer = ""
    !if $company != ""
        !$footer = $footer + $company
    !endif
    !if $confidential == %true()
        !if %strlen($footer) > 0
            !$footer = $footer + " - "
        !endif
        !$footer = $footer + "<color:red>Confidential</color>"
    !endif

    !if $footer != ""
        ' add linebreak for spacing
        footer \n$footer
    !endif
!endprocedure

!procedure $add_title($title="")
    !if $title != ""
        title $title
    !endif
!endprocedure

' ===
' Styling/Layout Helpers
' ===

!procedure $use_word_wrap($width = 125)
    skinparam wrapWidth $width
    skinparam wrapMessageWidth $width
    skinparam maxMessageSize $width
!endprocedure

!procedure $use_horizontal_layout()
    left to right direction
!endprocedure


' ===
' Styling/Theming
' ===

!function $get_themed_value($key, $prefix="")
    ' TODO: add assert for key existence (once plantuml adds ability to check)
    ' TODO: fallback to unprefixed key value if no key exists with prefix

    !if %strlen($prefix) > 0
        !$prefixed_key = $prefix + "_" + $key
        !return $theme_data[$prefixed_key]
    !endif

    !return $theme_data[$key]
!endfunction

!procedure $apply_base_styles()
    skinparam actorStyle awesome
    skinparam backgroundcolor $get_themed_value("canvasBackgroundColor")
    skinparam shadowing false
    skinparam padding 2
    skinparam defaultFontName $get_themed_value("textFont")
    skinparam defaultMonospacedFontName $get_themed_value("codeFont")
    skinparam defaultFontSize $get_themed_value("bodyFontSize")
    skinparam roundCorner 5

    skinparam Title {
        FontSize $get_themed_value("titleFontSize")
    }

    skinparam Footer {
        FontSize $get_themed_value("infoFontSize")
    }

    skinparam Header {
        FontSize $get_themed_value("infoFontSize")
    }

    skinparam Arrow {
        Thickess 1
        Color $get_themed_value("arrowColor")
        FontColor $get_themed_value("labelFontColor")
    }

    skinparam Note {
        BackgroundColor $get_themed_value("bodyBackgroundColor", "note")

        FontSize $get_themed_value("bodyFontSize", "note")

        BorderColor $get_themed_value("borderColor", "note")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Legend {
        FontColor $get_themed_value("bodyFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor", "legend")

        BorderColor $get_themed_value("borderColor", "legend")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Label {
        FontColor $get_themed_value("labelFontColor")
    }

    skinparam Circle {
        FontColor $get_themed_value("labelFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    ' NOTE: looks like this is styling Circle
    skinparam Interface {
        FontColor $get_themed_value("labelFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Database {
        FontColor $get_themed_value("bodyFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        ' NOTE: BorderThickness not supported yet
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Boundary {
        FontColor $get_themed_value("labelFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Control {
        FontColor $get_themed_value("labelFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Entity {
        FontColor $get_themed_value("labelFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Collections {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Queue {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Artifact {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Agent {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Actor {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        FontColor $get_themed_value("labelFontColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Package {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        ' NOTE: cant set the title and description differently
        FontStyle Normal

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Usecase {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Node {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Folder {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Component {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Cloud {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Frame {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Card {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Rectangle {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Hexagon {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Storage {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Stack {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Person {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam File {
        BackgroundColor $get_themed_value("bodyBackgroundColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Class {
        HeaderBackgroundColor $get_themed_value("headerBackgroundColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")
        BorderColor $get_themed_value("borderColor")
        FontSize $get_themed_value("headerFontSize")
        FontStyle $get_themed_value("headerFontStyle")
        FontColor $get_themed_value("headerFontColor")

        AttributeFontSize $get_themed_value("bodyFontSize")
        AttributeFontColor $get_themed_value("bodyFontColor")
        AttributeFontName $get_themed_value("codeFont")
    }

    skinparam State {
        BackgroundColor $get_themed_value("bodyBackgroundColor")
        FontStyle $get_themed_value("headerFontStyle")
        FontSize $get_themed_value("headerFontSize")
        FontColor $get_themed_value("bodyFontColor")

        AttributeFontSize $get_themed_value("bodyFontSize")
        AttributeFontColor $get_themed_value("bodyFontColor")

        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness")
    }

    skinparam Object {
        BackgroundColor $get_themed_value("bodyBackgroundColor")
        BorderColor $get_themed_value("borderColor")
        FontSize $get_themed_value("headerFontSize")
        FontStyle $get_themed_value("headerFontStyle")
        FontColor $get_themed_value("headerFontColor")

        AttributeFontSize $get_themed_value("bodyFontSize")
        AttributeFontColor $get_themed_value("bodyFontColor")
    }

    ' used in class, object, and activity diagrams
    skinparam ActivityDiamond {
        BackgroundColor $get_themed_value("headerBackgroundColor")
        BorderColor $get_themed_value("borderColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }
!endprocedure

' Diagram specific styles (should follow $apply_*_styles() naming convention)
' Override or extend anything not already defined in the standard styles

!procedure $apply_activity_styles()
    ' hide merge diamonds
    skinparam ConditionEndStyle hline

    ' should mimic state styling
    skinparam Activity {
        FontStyle Normal
        FontColor $get_themed_value("bodyFontColor")
        BackgroundColor $get_themed_value("bodyBackgroundColor")
        BorderColor $get_themed_value("borderColor")

        Diamond {
            FontStyle Bold
            FontColor $get_themed_value("headerFontColor")
            BorderThickness $get_themed_value("borderThickness")
        }
    }

    skinparam Swimlane {
        TitleFontSize $get_themed_value("subtitleFontSize")
        ' TODO: add into theme json
        BorderColor SlateGray
        BorderThickness 3
    }
!endprocedure

!procedure $apply_sequence_styles()
    autonumber
    autoactivate on
    hide unlinked

    skinparam actorStyle stick
    skinparam style strictuml
    skinparam boxPadding 10

    skinparam Sequence {
        ArrowThickness 2

        Participant {
            BackgroundColor $get_themed_value("bodyBackgroundColor")
            BorderColor $get_themed_value("borderColor")
            ' use border consistent with other sequence symbols
            BorderThickness $get_themed_value("borderThickness", "symbol")
        }

        LifeLine {
            BorderColor $get_themed_value("headerBackgroundColor")
            BackgroundColor $get_themed_value("bodyBackgroundColor")
        }

        Box {
            BackgroundColor $get_themed_value("containerBackgroundColor")
            BorderColor $get_themed_value("borderColor")
            ' NOTE: border thickness not supported on box
            BorderThickness $get_themed_value("borderThickness")
        }

        Delay {
            FontColor $get_themed_value("labelFontColor")
            FontStyle Italic
        }

        Group {
            BackgroundColor $get_themed_value("headerBackgroundColor")
            BorderColor $get_themed_value("borderColor")
            BorderThickness $get_themed_value("borderThickness")
            BodyBackgroundColor Transparent
        }

        Reference {
            HeaderBackgroundColor $get_themed_value("headerBackgroundColor")
            BorderColor $get_themed_value("borderColor")
            BorderThickness $get_themed_value("borderThickness")
            BodyBackgroundColor Transparent
        }

        Divider {
            BackgroundColor $get_themed_value("headerBackgroundColor", "sequenceDivider")
            BorderColor $get_themed_value("borderColor", "sequenceDivider")
            BorderThickness 1
            FontStyle Bold
        }

    }

    skinparam Database {
        ' sequence shows databases as a symbol instead of a container with stuff inside
        FontColor $get_themed_value("labelFontColor")
        ' NOTE: BorderThickness not supported yet
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Queue {
        ' sequence shows databases as a symbol instead of a container with stuff inside
        FontColor $get_themed_value("labelFontColor")
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }

    skinparam Collections {
        ' use border consistent with other sequence symbols
        BorderThickness $get_themed_value("borderThickness", "symbol")
    }
!endprocedure

!procedure $apply_state_styles()
    hide empty description

    skinparam State<<composite>> {
        BackgroundColor $get_themed_value("headerBackgroundColor")
        FontStyle $get_themed_value("headerFontStyle")
        FontSize $get_themed_value("headerFontSize")
        FontColor $get_themed_value("headerFontColor")
    }

    skinparam State {
        ' TODO: add these into theme?
        BackgroundColor<<todo>> RoyalBlue
        BorderColor<<todo>> MediumBlue
        FontColor<<todo>> White
        AttributeFontColor<<todo>> White
    }

    skinparam State {
        BackgroundColor<<inprogress>> Gold
        BorderColor<<inprogress>> GoldenRod
        AttributeFontColor<<inprogress>> Black
    }

    skinparam State {
        BackgroundColor<<done>> ForestGreen
        BorderColor<<done>> DarkGreen
        FontColor<<done>> White
        AttributeFontColor<<done>> White
    }
!endprocedure

!procedure $apply_class_styles()
    set namespaceSeparator ::

    skinparam Package {
        Style Frame
        FontStyle Bold
    }

    skinparam Stereotype {
        C {
            BackgroundColor $get_themed_value("bodyBackgroundColor")
            BorderColor $get_themed_value("borderColor")
        }
    }

    ' NOTE: this is styling Circle (bug in plantuml)
    skinparam Interface {
        BackgroundColor $get_themed_value("headerBackgroundColor")
    }
!endprocedure

!procedure $apply_er_styles()
    ' ER diagrams are pretty much class diagrams
    $apply_class_styles()

    ' https://github.com/plantuml/plantuml/pull/31
    hide circle
    hide empty members
    hide stereotype
    skinparam linetype ortho

    skinparam Package {
        Style Frame
        FontStyle Bold
    }

    skinparam Class {
        AttributeFontName<<table>> $get_themed_value("codeFont")
    }

    skinparam Class {
        BorderColor<<enum>> $get_themed_value("borderColor", "enum")
        HeaderBackgroundColor<<enum>> $get_themed_value("headerBackgroundColor", "enum")
        BackgroundColor<<enum>> $get_themed_value("bodyBackgroundColor", "enum")

        AttributeFontName<<enum>> $get_themed_value("codeFont")
    }
!endprocedure

!procedure $apply_usecase_styles()
    skinparam Package {
        Style Rectangle
        FontStyle Bold
        ' NOTE: it seems Rectange's styling is overwritting this?
        BackgroundColor $get_themed_value("containerBackgroundColor")
    }
!endprocedure

!procedure $apply_object_styles()
    ' object diagrams are pretty much class diagrams
    $apply_class_styles()

    hide circle
    set namespaceSeparator none

    skinparam Package {
        Style Rectangle
        BackgroundColor $get_themed_value("containerBackgroundColor")
    }
!endprocedure

!procedure $apply_generic_styles()
    ' intentionally left blank
!endprocedure

!procedure $apply_deployment_styles()
    ' intentionally left blank
!endprocedure


' ===
' Library Macros/Procs
' ===

!procedure Enrich($diagram="generic", $title="", $company="", $author="", $revision="", $confidential=%true())
    ' apply styles
    !$diagram_style_proc_name = "$apply_" + $diagram + "_styles"
    !assert %function_exists($diagram_style_proc_name) : "Unknown diagram type for '" + $diagram + "'."
    $apply_base_styles()
    %invoke_procedure($diagram_style_proc_name)

    ' add meta info
    $add_header($author, $revision, $title)
    $add_footer($company, $confidential)
    $add_title($title)
!endprocedure


' ===
' ER Diagram Macros/Procs
' ===

!procedure SET_SCHEMA_DEFAULTS($id_name="", $id_type="", $poly_type_type="", $poly_id_suffix="", $poly_type_suffix="")
    !if $id_name != ""
        !global $ID_NAME = $id_name
    !endif
    !if $id_type != ""
        !global $ID_TYPE = %upper($id_type)
    !endif
    !if $poly_type_type != ""
        !global $POLY_TYPE_TYPE = %upper($poly_type_type)
    !endif
    !if $poly_id_suffix != ""
        !global $POLY_ID_SUFFIX = %upper($poly_id_suffix)
    !endif
    !if $poly_type_suffix != ""
        !global $POLY_TYPE_SUFFIX = %upper($poly_type_suffix)
    !endif
!endprocedure

SET_SCHEMA_DEFAULTS($id_name="id", $id_type="INTEGER(11)", $poly_type_type="VARCHAR", $poly_id_suffix="_id", $poly_type_suffix="_type")

!unquoted procedure Table($name)
    Entity $name<<table>>
!endprocedure

!unquoted procedure PartialTable($name)
    Table($name)<<partial>> {
        ---
        table_pk()
        omitted_columns()
    }
!endprocedure

!unquoted procedure EnumType($name, $type)
    Enum $name<$type><<enum>>
!endprocedure

!unquoted procedure enum_value($name, $value)
    {field} - <b>$name</b>: $value
!endprocedure

!unquoted procedure PolymorphicLink($name)
    Abstract $name<polymorphic><<polymorphic>>
!endprocedure)

!define poly_assoc(name) abstract name<polymorphic>

!define has_one(from, to) from }--|| to
!define has_one_poly(from, to) from }-- to
!define poly_can_be(from, to) from --|| to
!define has_one_to_one(from, to) from ||--|| to
!define has_many(from, to) from }--{ to
!define column_pk(name = "id") {field} {static}{method} # <b>name</b>: $ID_TYPE
!define column_pk(name = "id", type) {static}{method} # <b>name</b>: type
!define column_fk(name) {method} + <b>name</b>: $ID_TYPE
!define column_fk(name, type) {method} + <b>name</b>: type
!definelong column_fk_poly(name, type_type="VARCHAR", id_suffix = "_id", type_suffix = "_type")
    {method} + <b>name##id_suffix</b>: $ID_TYPE
    {field} + <b>name##type_suffix</b>: type_type
!enddefinelong
!define column_non_nullable(name, type) {field} + <b>name</b>: type
!define column_nullable(name, type) {field} + <b>name</b>: type
!define omitted_columns(name = "...") //name//

!definelong timestamps()
    column_non_nullable(created_at, DATETIME)
    column_non_nullable(updated_at, DATETIME)
!enddefinelong
